In [20]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))
from wanna_buy_house.data import *
from wanna_buy_house import utils
import joblib
import pandas as pd

In [11]:
os.path
os.getcwd()
os.path.join(os.getcwd(), '..')
os.path.dirname(os.getcwd())

'/Users/sanderiwase/code/sanderiw/project493'

In [13]:
sys.path

['/Users/sanderiwase/code/sanderiw/project493/notebooks',
 '/Users/sanderiwase/code/sanderiw/data-challenges/04-Decision-Science',
 '/Users/sanderiwase/code/sanderiw/project493/notebooks',
 '/Users/sanderiwase/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python37.zip',
 '/Users/sanderiwase/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python3.7',
 '/Users/sanderiwase/.pyenv/versions/3.7.7/lib/python3.7/lib-dynload',
 '',
 '/Users/sanderiwase/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages',
 '/Users/sanderiwase/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/IPython/extensions',
 '/Users/sanderiwase/.ipython',
 '/Users/sanderiwase/code/sanderiw/project493']

In [14]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))
from wanna_buy_house import data
from wanna_buy_house import utils
data = data.final_treatment()

get_data 0.37

In [15]:
data

,Current.Loan.Amount,Term,Home.Ownership,Annual.Income,Current.Credit.Balance,Loan.Status,Number.of.Open.Accounts.Buckets,Credit.Minus.Loan,Number.of.Credit.Problems.Buckets,Years.current_job_enc,Purpose_enc,Tax.Liens.Enc,leverage,Credit.Score.Enc,Year.Credit.History.Enc,Bankruptcies.enc,Years.since.last.delinquent,Loan.vs.Income
0,17879,Short Term,Home Mortgage,95357.0,23986,1,mais de 20,1,0,6,Debt Consolidation,0,0.190000,Excellent,30+,0,1,0.187495
3,11200,Short Term,Rent,53965.0,11782,1,0-10,1,1,4,Debt Consolidation,0,0.301998,Excellent,10.1 a 20,1,0,0.207542
4,3608,Short Term,Home Mortgage,47709.0,22909,1,0-10,1,0,10,Home Improvements,0,0.085501,Excellent,10.1 a 20,0,0,0.075625
5,7877,Short Term,Home Mortgage,47707.0,1837,1,11-20,0,1,5,Home Improvements,0,0.127000,Excellent,10.1 a 20,1,0,0.165112
6,4732,Long Term,Rent,62721.0,0,0,0-10,0,0,10,Other,0,0.056798,Good,20.1 a 30,0,0,0.075445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60794,14885,Short Term,Rent,124875.0,14684,1,11-20,0,0,6,Debt Consolidation,0,0.047101,Excellent,0 a 10,0,0,0.119199
60795,5086,Short Term,Home Mortgage,50855.0,7671,1,11-20,1,0,1,Debt Consolidation,0,0.197000,Excellent,10.1 a 20,0,0,0.100010
60797,27840,Long Term,Home Mortgage,99430.0,34938,1,mais de 20,1,0,10,Debt Consolidation,0,0.292000,Below Average,30+,0,0,0.279996
60800,18229,Short Term,Rent,91143.0,8328,0,11-20,0,0,3,Debt Consolidation,0,0.103000,Excellent,10.1 a 20,0,1,0.200004
60803,2866,Short Term,Home Mortgage,42991.0,39,1,0-10,0,0,8,Debt Consolidation,0,0.325003,Good,20.1 a 30,0,0,0.066665

In [16]:
pipeline = joblib.load('../model.joblib')

In [17]:
input_teste = pd.DataFrame({'Loan.ID': [0],
						 'Current.Loan.Amount': [17879],
						 'Term': ['Short Term'],
						 'Credit.Score': [739.0],
						 'Years.in.current.job': ['6 years'],
						 'Home.Ownership': ['Home Mortgage'],
						 'Annual.Income': [95357.0],
						 'Purpose': ['Debt Consolidation'],
						 'Monthly.Debt': [1509.82],
						 'Years.of.Credit.History': [34.4],
						 'Months.since.last.delinquent': [5.0],
						 'Number.of.Open.Accounts': [26],
						 'Number.of.Credit.Problems': [0],
						 'Current.Credit.Balance': [23986],
						 'Maximum.Open.Credit': [40313],
						 'Bankruptcies': [0.0],
						 'Tax.Liens': [0.0]})

In [18]:
input_teste

,Loan.ID,Current.Loan.Amount,Term,Credit.Score,Years.in.current.job,Home.Ownership,Annual.Income,Purpose,Monthly.Debt,Years.of.Credit.History,Months.since.last.delinquent,Number.of.Open.Accounts,Number.of.Credit.Problems,Current.Credit.Balance,Maximum.Open.Credit,Bankruptcies,Tax.Liens
0,0,17879,Short Term,739.0,6 years,Home Mortgage,95357.0,Debt Consolidation,1509.82,34.4,5.0,26,0,23986,40313,0.0,0.0

In [53]:
xx = pipeline.predict_proba(data.head(100))

/Users/sanderiwase/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/sklearn/compose/_column_transformer.py:440: FutureWarning: Given feature/column names or counts do not match the ones for the data given during fit. This will fail from v0.24.
  FutureWarning)

In [68]:
data = get_data()
data = clean_data(data)
data.head(50)

get_data 0.36

,Loan.ID,Current.Loan.Amount,Term,Credit.Score,Years.in.current.job,Home.Ownership,Annual.Income,Purpose,Monthly.Debt,Years.of.Credit.History,Months.since.last.delinquent,Number.of.Open.Accounts,Number.of.Credit.Problems,Current.Credit.Balance,Maximum.Open.Credit,Bankruptcies,Tax.Liens,Loan.Status
0,0,17879,Short Term,739.0,6 years,Home Mortgage,95357.0,Debt Consolidation,1509.82,34.4,5.0,26,0,23986,40313,0.0,0.0,1
3,4,11200,Short Term,738.0,4 years,Rent,53965.0,Debt Consolidation,1358.11,15.8,NaN,8,1,11782,25951,1.0,0.0,1
4,5,3608,Short Term,731.0,10+ years,Home Mortgage,47709.0,Home Improvements,339.93,16.1,47.0,6,0,22909,25568,0.0,0.0,1
5,7,7877,Short Term,738.0,5 years,Home Mortgage,47707.0,Home Improvements,504.90,14.5,70.0,10,1,1837,6269,1.0,0.0,1
6,8,4732,Long Term,701.0,10+ years,Rent,62721.0,other,296.87,20.2,51.0,2,0,0,0,0.0,0.0,0
7,10,3469,Short Term,735.0,5 years,Rent,25135.0,Debt Consolidation,354.83,9.1,NaN,7,0,3646,6840,0.0,0.0,0
8,11,10031,Short Term,712.0,6 years,Rent,150465.0,other,1199.96,12.5,20.0,9,0,17885,22583,0.0,0.0,1
10,15,20044,Short Term,741.0,3 years,Home Mortgage,91200.0,Debt Consolidation,703.76,14.9,NaN,8,0,20523,25369,0.0,0.0,1
13,18,4836,Short Term,723.0,10+ years,Home Mortgage,75563.0,Debt Consolidation,585.61,13.4,NaN,13,0,22361,30341,0.0,0.0,1
14,19,6162,Short Term,684.0,10+ years,Home Mortgage,74154.0,Debt Consolidation,1044.33,15.7,56.0,13,0,4967,14395,0.0,0.0,0
15,21,15538,Short Term,709.0,6 years,Home Mortgage,87479.0,Debt Consolidation,1297.61,15.0,41.0,19,1,7687,14559,0.0,0.0,1
16,22,5917,Short Term,745.0,6 years,Home Mortgage,69034.0,Business Loan,1353.07,18.5,NaN,8,0,18112,21690,0.0,0.0,0
17,23,5066,Short Term,745.0,3 years,Home Mortgage,75983.0,Debt Consolidation,1386.68,16.6,13.0,16,0,7022,32659,0.0,0.0,1
18,25,32596,Long Term,739.0,1 year,Home Mortgage,175680.0,Home Improvements,2078.88,19.6,NaN,9,0,19097,27127,0.0,0.0,1
19,26,5409,Short Term,744.0,4 years,Rent,140641.0,moving,890.73,19.1,23.0,13,0,16463,68882,0.0,0.0,1
20,28,18295,Long Term,692.0,10+ years,Home Mortgage,51836.0,Debt Consolidation,622.04,38.4,NaN,20,0,18642,40971,0.0,0.0,1
22,31,4970,Short Term,707.0,less than 1 year,Rent,34790.0,Debt Consolidation,472.57,8.0,NaN,7,0,4443,7754,0.0,0.0,1
23,33,2412,Short Term,739.0,8 years,Rent,25630.0,Debt Consolidation,281.93,12.5,NaN,14,1,7209,26213,1.0,0.0,1
24,34,25245,Long Term,711.0,5 years,Home Mortgage,68666.0,Debt Consolidation,1247.44,14.0,NaN,19,0,16270,40074,0.0,0.0,1
25,35,4895,Short Term,673.0,4 years,Rent,24473.0,Debt Consolidation,575.10,10.8,20.0,11,0,1414,11399,0.0,0.0,1
28,39,9758,Short Term,659.0,2 years,Rent,107338.0,Business Loan,512.54,10.0,30.0,5,0,2530,4487,0.0,0.0,1
29,40,14918,Short Term,744.0,10+ years,Home Mortgage,61659.0,Debt Consolidation,549.79,19.4,NaN,8,0,11083,21562,0.0,0.0,1
30,41,11588,Long Term,718.0,5 years,Home Mortgage,63745.0,Debt Consolidation,350.07,9.2,NaN,6,0,3491,7318,0.0,0.0,0
31,43,23942,Short Term,718.0,10+ years,Home Mortgage,84796.0,Debt Consolidation,1095.28,15.5,16.0,8,0,3831,4988,0.0,0.0,1
32,44,8158,Short Term,732.0,10+ years,Rent,61188.0,Debt Consolidation,1101.38,23.0,66.0,11,1,6436,11514,1.0,0.0,1
34,47,11732,Short Term,743.0,less than 1 year,Home Mortgage,53774.0,Debt Consolidation,384.48,22.5,NaN,12,1,12671,55820,1.0,0.0,1
35,49,30078,Long Term,695.0,10+ years,Home Mortgage,148385.0,Debt Consolidation,1681.69,18.5,74.0,18,0,22469,72482,0.0,0.0,0
36,51,4898,Short Term,722.0,less than 1 year,Home Mortgage,117346.0,Debt Consolidation,226.87,25.5,40.0,8,1,283,4791,0.0,0.0,1
37,52,6820,Short Term,722.0,8 years,Home Mortgage,34476.0,Debt Consolidation,775.71,13.8,NaN,10,0,33069,35292,0.0,0.0,1
39,54,4965,Short Term,743.0,10+ years,Home Mortgage,115188.0,Debt Consolidation,1699.02,21.6,NaN,11,0,34614,59169,0.0,0.0,1
40,55,8887,Short Term,722.0,10+ years,Rent,35546.0,Debt Consolidation,906.43,14.9,NaN,13,0,13950,23604,0.0,0.0,1
42,58,6278,Short Term,741.0,less than 1 year,Rent,81672.0,Debt Consolidation,1994.15,24.7,NaN,12,0,23824,29232,0.0,0.0,1
50,70,14155,Short Term,743.0,less than 1 year,Home Mortgage,58980.0,Debt Consolidation,1012.49,15.8,16.0,8,0,19240,56258,0.0,0.0,1
52,72,20656,Short Term,726.0,10+ years,Rent,98360.0,Debt Consolidation,1278.68,17.1,31.0,7,0,6056,7774,0.0,0.0,0
55,76,9911,Short Term,719.0,2 years,Rent,49559.0,small_business,685.56,15.8,45.0,6,0,750,3277,0.0,0.0,1
56,77,21795,Long Term,680.0,10+ years,Own Home,106996.0,Debt Consolidation,1551.44,12.8,NaN,16,0,35524,58620,0.0,0.0,1
58,80,4959,Short Term,719.0,4 years,Rent,124967.0,Debt Consolidation,1812.02,14.0,NaN,10,0,24549,32344,0.0,0.0,1
59,82,15775,Long Term,672.0,5 years,Home Mortgage,46736.0,Debt Consolidation,915.26,8.7,NaN,7,0,8012,9916,0.0,0.0,1
61,85,5204,Short Term,746.0,1 year,Rent,46149.0,Buy a Car,77.69,21.7,NaN,7,1,2788,10805,1.0,0.0,1
62,87,10141,Short Term,693.0,1 year,Rent,79100.0,Debt Consolidation,181.27,7.6,NaN,4,0,6640,8819,0.0,0.0,1
63,88,12322,Short Term,724.0,9 years,Own Home,35930.0,Debt Consolidation,733.56,11.1,NaN,4,0,5444,6979,0.0,0.0,1
64,89,4764,Short Term,741.0,6 years,Rent,79408.0,other,985.98,36.2,31.0,9,0,6158,7885,0.0,0.0,1
65,90,10814,Short Term,723.0,less than 1 year,Rent,52915.0,Debt Consolidation,1049.48,30.3,38.0,27,0,28471,44836,0.0,0.0,1
67,93,35676,Long Term,664.0,10+ years,Rent,254825.0,Debt Consolidation,1191.31,24.0,43.0,8,0,7885,9581,0.0,0.0,0
69,95,1948,Short Term,742.0,5 years,Own Home,28328.0,Debt Consolidation,757.76,10.8,53.0,6,0,2771,23092,0.0,0.0,1
71,98,15704,Long Term,698.0,10+ years,Home Mortgage,50057.0,Debt Consolidation,871.82,28.0,NaN,14,0,19869,22811,0.0,0.0,0
72,100,14763,Short Term,709.0,8 years,Rent,88578.0,Debt Consolidation,1831.35,22.3,NaN,16,0,33750,40131,0.0,0.0,1
75,105,34276,Short Term,678.0,1 year,Rent,146895.0,Business Loan,1407.74,15.7,19.0,8,0,1656,11040,0.0,0.0,1
77,107,10047,Short Term,709.0,10+ years,Rent,60282.0,Debt Consolidation,522.44,14.5,12.0,17,0,23218,53130,0.0,0.0,1
78,108,18599,Long Term,728.0,5 years,Rent,58734.0,Business Loan,974.01,12.5,8.0,13,0,4594,26402,0.0,0.0,0

In [56]:
data1 = pd.DataFrame(xx)
data1['true'] = x

In [67]:
data1.head(60)

           0         1  true
0   0.060000  0.940000     1
1   0.400000  0.600000     1
2   0.031304  0.968696     1
3   0.220000  0.780000     1
4   0.380000  0.620000     0
5   0.929474  0.070526     0
6   0.360000  0.640000     1
7   0.340000  0.660000     1
8   0.271304  0.728696     1
9   0.900000  0.100000     0
10  0.100000  0.900000     1
11  0.728810  0.271190     0
12  0.080000  0.920000     1
13  0.300000  0.700000     1
14  0.020000  0.980000     1
15  0.220000  0.780000     1
16  0.200000  0.800000     1
17  0.300000  0.700000     1
18  0.230000  0.770000     1
19  0.100000  0.900000     1
20  0.060000  0.940000     1
21  0.057030  0.942970     1
22  0.960000  0.040000     0
23  0.160000  0.840000     1
24  0.140000  0.860000     1
25  0.180000  0.820000     1
26  0.840000  0.160000     0
27  0.020000  0.980000     1
28  0.180000  0.820000     1
29  0.240000  0.760000     1
30  0.331000  0.669000     1
31  0.180000  0.820000     1
32  0.180000  0.820000     1
33  0.920000  0.080000     0
34  0.284000  0.716000     1
35  0.220000  0.780000     1
36  0.040000  0.960000     1
37  0.275385  0.724615     1
38  0.040000  0.960000     1
39  0.100000  0.900000     1
40  0.736079  0.263921     1
41  0.180000  0.820000     1
42  0.340000  0.660000     1
43  0.720000  0.280000     0
44  0.184500  0.815500     1
45  0.894545  0.105455     0
46  0.520000  0.480000     1
47  0.220000  0.780000     1
48  0.120000  0.880000     1
49  0.440000  0.560000     0
50  0.040000  0.960000     1
51  0.080000  0.920000     1
52  0.060000  0.940000     1
53  0.700000  0.300000     0
54  0.140000  0.860000     1
55  0.120000  0.880000     1
56  0.120000  0.880000     1
57  0.120000  0.880000     1
58  0.380000  0.620000     1
59  0.147500  0.852500     1

In [54]:
x = data.head(100)['Loan.Status'].reset_index().drop(columns='index')

In [55]:
x

    Loan.Status
0             1
1             1
2             1
3             1
4             0
..          ...
95            0
96            1
97            0
98            1
99            1

[100 rows x 1 columns]